# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['Renamica.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5.QtWebSockets',
        'PyQt5.QtQuick',
        'PyQt5.QtQml',
        'PyQt5.QtQmlModels',
        'PyQt5.QtPrintSupport',
        'PyQt5.QtDBus',
        'PyQt5.QtTest',
        'PyQt5.QtHelp',
        'PyQt5.QtMultimedia',
        'PyQt5.QtNetworkAuth',
        'PyQt5.QtOAuth',
        'PyQt5.QtRemoteObjects',
        'PyQt5.QtSensors',
        'PyQt5.QtSerialPort',
        'PyQt5.QtSpeech',
        'PyQt5.QtTextToSpeech',
        'PyQt5.QtXmlPatterns',
        'PyQt5.Qt3DInput',
        'PyQt5.Qt3DCore',
        'PyQt5.Qt3DRender',
        'PyQt5.Qt3DLogic',
        'PyQt5.Qt3DExtras',
        'PyQt5.QtCharts',
        'PyQt5.QtDataVisualization',
        'PyQt5.QtScxml',
        'PyQt5.QtStateMachine',
        'PyQt5.QtLocation',
        'PyQt5.QtPositioning',
        'PyQt5.QtWebEngine',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtWebEngineWidgets',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Renamica',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='renamica.icns',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Renamica',
)

app = BUNDLE(
    coll,
    name='Renamica.app',
    icon='renamica.icns',
    bundle_identifier='com.renamica.app',
    version='1.0.0',
    info_plist={
        'CFBundleName': 'Renamica',
        'CFBundleDisplayName': 'Renamica',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'CFBundleDevelopmentRegion': 'zh_CN',
        'NSHighResolutionCapable': True,
        'NSSupportsAutomaticGraphicsSwitching': True,
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'All Files',
                'CFBundleTypeRole': 'Editor',
                'LSHandlerRank': 'Default',
                'LSItemContentTypes': ['public.data'],
            },
        ],
    },
)
